//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOP_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftAppDBEntities : DbContext
    {
        public GiftAppDBEntities()
            : base("name=GiftAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventTbl> EventTbls { get; set; }
        public virtual DbSet<GiftTbl> GiftTbls { get; set; }
        public virtual DbSet<PersonTbl> PersonTbls { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
