//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOP_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftTbl
    {
        public int GiftId { get; set; }
        public string GiftName { get; set; }
        public int EventId { get; set; }
        public decimal GiftPrice { get; set; }
    
        public virtual EventTbl EventTbl { get; set; }
    }
}
