//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOP_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonTbl()
        {
            this.EventTbls = new HashSet<EventTbl>();
        }
    
        public int PersonId { get; set; }
        public int UserId { get; set; }
        public string PersonName { get; set; }
        public System.DateTime PersonDOB { get; set; }
        public string PersonGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTbl> EventTbls { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
